### PR TITLE
update versions due to new cloudshell-automation-api package

### PR DESCRIPTION
**Pull request by MeirAtWork**
updated new cloudshell-automation-api version

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/141)

### CODE REVIEW

**Comment by TomerAdmon** [comment]
@MeirAtWork  - Please change the requirements to use major.minor.0.0 and to have a higher and lower number.
for example cloudshell-automation-api>=2020.1.0.0,<2020.2.0.0

**Comment by TomerAdmon** [comment]
@MeirAtWork  - Please bump the version of cloudshell-orch-core as we don't want existing customers (using 9.3 and down) to get the new cloudshell-autonation-api.

**Comment by MeirAtWork** [comment]
@TomerAdmon i have already bumped cloudshell-orch-core version - to 3.3.0.1

**Comment by TomerAdmon** [comment]
Thanks @MeirAtWork .

Currently, our latest version of orch-core released to pypi is  3.2.0.X which means the next version will be indeed 3.3.0.X.
The X part is set by TeamCity as the build number - no need to provide that number in the repo.

So, if the next version of orch-core that we will release in Pypi is 3.3.0.X we will need all orchestration scripts that should use it to have the following requirements:
cloudshell-orch-core>=3.3.0.0,<3.4.0.0
As we don't want existing customers to take that version, it might break something for them.

The version.txt should match the orch-core version, so let's change that as well to be 3.3.0

cloudshell-automation-api version should be between 2020.1 to 2020.2 --> 2020.2 will be released is a few months, so the current requirement you specified won't be met till then... It's probably more suitable to use:
cloudshell-automation-api>=2020.1.0.0,<2020.2.0.0

**Comment by MeirAtWork** [comment]
@TomerAdmon is it OK now?

**Comment by TomerAdmon** [comment]
Just update the version from 3.3.0.1 to 3.3.0

**Comment by MeirAtWork** [comment]
@TomerAdmon  check now

**Review by TomerAdmon — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/141)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
