### PR TITLE
added support for calling connect_child_resources if it exists on dep…

### PR DESCRIPTION
**Pull request by nahumtimerman**
…loyed app, after autoload, which remaps connections from chassis to ports

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/17)

### CODE REVIEW

**Comment by alexazarh** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[sandbox_scripts/environment/setup/setup_script.py, line 88 \[r1\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOij_iXtd8wNUs1CY7P:-KOij_iXtd8wNUs1CY7Q:b-a7a02q) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/484e9e22a8b6b92b728186cd7cc8b6c0a37d6baf/sandbox_scripts/environment/setup/setup_script.py#L88)):*
> ```Python
>         if deploy_result is None:
>             self.logger.info("No apps to remap")
>             api.WriteMessageToReservationOutput(reservationId=self.reservation_id, message='No apps to remap')
> ```

I think we can remove this message to the output

---

*[sandbox_scripts/environment/setup/setup_script.py, line 105 \[r1\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOioHYc2-m4hEhzFIfT:-KOioHYc2-m4hEhzFIfU:b-z1hoek) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/484e9e22a8b6b92b728186cd7cc8b6c0a37d6baf/sandbox_scripts/environment/setup/setup_script.py#L105)):*
> ```Python
>             if autoload.lower() != "true":
>                 self.logger.info("Apps discovery is disabled on deployed app {0}".format(deployed_app_name))
>                 continue
> ```

lets move this into the _try_exeucte_autoload method

---

*[sandbox_scripts/environment/setup/setup_script.py, line 119 \[r1\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOipPCPqqZevmjN_zcG:-KOipPCPqqZevmjN_zcH:bdbb7ii) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/484e9e22a8b6b92b728186cd7cc8b6c0a37d6baf/sandbox_scripts/environment/setup/setup_script.py#L119)):*
> ```Python
>             except CloudShellAPIError as exc:
>                 if exc.code not in (EnvironmentSetup.NO_DRIVER_ERR, EnvironmentSetup.DRIVER_FUNCTION_ERROR,
>                                     c.MISSING_COMMAND_ERROR):
> ```

add this errror type also to the _try_exeucte_autoload method

---

*[sandbox_scripts/environment/setup/setup_script.py, line 214 \[r1\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOip_i2XsKgf5ImpWJG:-KOip_i2XsKgf5ImpWJH:b51cfdw) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/484e9e22a8b6b92b728186cd7cc8b6c0a37d6baf/sandbox_scripts/environment/setup/setup_script.py#L214)):*
> ```Python
>         :param CloudShellAPISession api:
>         :param GetReservationDescriptionResponseInfo reservation_details:
>         :param str reservation_id:
> ```

resource_details_cache is missing from doc string

---

*[SandboxOrchestrationPackage/Topology Scripts/Default Sandbox Setup.zip, line 0 \[r1\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOiq_dr_N7Qdg6jxkd_:-KOiq_dr_N7Qdg6jxkda:b-54alja) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/484e9e22a8b6b92b728186cd7cc8b6c0a37d6baf/SandboxOrchestrationPackage/Topology Scripts/Default Sandbox Setup.zip#L0)):*
please add to git ignore :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by alexazarh** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[.idea/dictionaries/nahum_t.xml, line 7 \[r2\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOth8smjMHWpO8iYZtF:-KOth8snprn_HET5ne3n:b-aflr8e) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/4f7e6169891101c2516e837b5439d994ac10c7a0/.idea/dictionaries/nahum_t.xml#L7)):*
> ```XML
>     </words>
>   </dictionary>
> </component>
> ```

what is this?

---

*[sandbox_scripts/environment/setup/setup_script.py, line 8 \[r2\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOthVYOmVrqT8219QAh:-KOthVYOmVrqT8219QAi:b9m0rfj) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/4f7e6169891101c2516e837b5439d994ac10c7a0/sandbox_scripts/environment/setup/setup_script.py#L8)):*
> ```Python
> from cloudshell.api.common_cloudshell_api import CloudShellAPIError
> from cloudshell.core.logger.qs_logger import get_qs_logger
> import remap_child_resources_constants as c
> ```

Please use meaningful name 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by alexazarh** [comment]
Reviewed 4 of 5 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by nahumtimerman** [comment]
*[sandbox_scripts/environment/setup/setup_script.py, line 8 \[r2\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOthVYOmVrqT8219QAh:-KOtismbAjXUO0O6N8RZ:bs7b68t) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/4f7e6169891101c2516e837b5439d994ac10c7a0/sandbox_scripts/environment/setup/setup_script.py#L8)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> Please use meaningful name 
</details>
its just a shortcut to bring in constants... I preferred that to adding the constants in the class, but I still want it very very short, coz the constants name is very descriptive and long

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by nahumtimerman** [comment]
*[sandbox_scripts/environment/setup/setup_script.py, line 88 \[r1\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOij_iXtd8wNUs1CY7P:-KOtj7vO47cdZz1Nubqh:b-glruci) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/484e9e22a8b6b92b728186cd7cc8b6c0a37d6baf/sandbox_scripts/environment/setup/setup_script.py#L88)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> I think we can remove this message to the output
</details>
I can remove it, but it was already there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by nahumtimerman** [comment]
*[.idea/dictionaries/nahum_t.xml, line 7 \[r2\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOth8smjMHWpO8iYZtF:-KOtjJXXTfrmY039V1Hz:b-1hb7ll) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/4f7e6169891101c2516e837b5439d994ac10c7a0/.idea/dictionaries/nahum_t.xml#L7)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> what is this?
</details>
looks like pycharm ide metadata. was not supposed to be added to commit, I'll remove it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by nahumtimerman** [comment]
*[SandboxOrchestrationPackage/Topology Scripts/Default Sandbox Setup.zip, line  \[r1\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOiq_dr_N7Qdg6jxkd_:-KOtjQZXMYwf_c2kcuBh:b-fucfg7) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/484e9e22a8b6b92b728186cd7cc8b6c0a37d6baf/SandboxOrchestrationPackage/Topology Scripts/Default Sandbox Setup.zip#L)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> please add to git ignore :)
</details>
its already in git ignore, I don't understand why it gets added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by alexazarh** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[.idea/dictionaries/nahum_t.xml, line 7 \[r2\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOth8smjMHWpO8iYZtF:-KOtk-lnt_iI50iMDZRa:bk7rc0l) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/4f7e6169891101c2516e837b5439d994ac10c7a0/.idea/dictionaries/nahum_t.xml#L7)):*
<details><summary><i>Previously, nahumtimerman wrote…</i></summary>
> looks like pycharm ide metadata. was not supposed to be added to commit, I'll remove it
</details>
In my opinion you must use descriptive names in Python especially because its not a strongly typed language

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by alexazarh** [comment]
*[sandbox_scripts/environment/setup/setup_script.py, line 8 \[r2\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOthVYOmVrqT8219QAh:-KP7fpZxxLmNdk8RDjwA:bk7rc0l) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/4f7e6169891101c2516e837b5439d994ac10c7a0/sandbox_scripts/environment/setup/setup_script.py#L8)):*
<details><summary><i>Previously, nahumtimerman wrote…</i></summary>
> its just a shortcut to bring in constants... I preferred that to adding the constants in the class, but I still want it very very short, coz the constants name is very descriptive and long
</details>
In my opinion you must use descriptive names in Python especially because its not a strongly typed language

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by nahumtimerman** [comment]
*[sandbox_scripts/environment/setup/setup_script.py, line 8 \[r2\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17#-KOthVYOmVrqT8219QAh:-KPg1QNZGsT1U-UaRjQ0:b14x9l3) ([raw file](https://github.com/qualisystems/cloudshell-orch-sandbox/blob/4f7e6169891101c2516e837b5439d994ac10c7a0/sandbox_scripts/environment/setup/setup_script.py#L8)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> In my opinion you must use descriptive names in Python especially because its not a strongly typed language
</details>
ok, handled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Comment by alexazarh** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-orch-sandbox/17)*

**Pull request merged**
